name: tsundoku
version: '0.1.1.0'
synopsis: Tsundoku tracks your piles of unread books.
description: Please see README.md
category: App
author: Isaac Azuelos
maintainer: isaac@azuelos.ca
copyright: 2016 Isaac Azuleos
license: MIT
github: isaacazuelos/tsundoku
dependencies:
- base
library:
  source-dirs: src
  dependencies:
  - text
  - time
  - aeson
  - bytestring
  - directory
  - semigroups
  - filepath
  - optparse-applicative
executables:
  doku:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tsundoku
    - optparse-applicative
    - text
tests:
  tests:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory
    - filepath
    - hspec
    - QuickCheck
    - tsundoku